language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - '8'
before_script:
  - npm prune
script:
  # check syntax of the script
  - node -c bin/commit-message-install.js
  - node -c bin/commit-message-run.js
  - $(npm bin)/if-node-version ">=6" npm test
  - DEBUG=commit-message-install node ./bin/commit-message-install.js
  # synthetic test case
  - DEBUG=commit-message-install node ./bin/commit-message-install.js -f test/message.txt
  - npm run demo
after_success:
  - $(npm bin)/if-node-version ">=8" npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
